# Generated by Django 4.1.3 on 2022-11-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
