# Generated by Django 4.1.3 on 2022-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_text_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
