# Generated by Django 4.1.3 on 2022-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_text_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=10)),
            ],
        ),
    ]
